// react-hooks-develop/src/components/Header/Header.component.jsx
import React from 'react';
import './Header.component.scss';
const Header = () => {
  return (
    <header className='globalHeader'>
      <nav>
        <ul>
          <li>
            <a href='/todo/js-version'>Vanilla</a>
          </li>
          <li>
            <a href='/todo/jq-version'>JQuery</a>
          </li>
          <li>
            <a href='/todo/vue'>Vue</a>
          </li>
          <li>
            <a href='/todo/react' className='active'>
              React
            </a>
          </li>
        </ul>
      </nav>
    </header>
  );
};

export default Header;

// vue-version/src/components/Header.vue
<template>
  <div>
    <div id="nav">
      <a href="/todo/js-version/" class="active">Vanilla</a>|
      <a href="/todo/jq-version/">JQuery</a>|
      <router-link to="vue" class="active">Vue</router-link>
    </div>
  </div>
</template>
<style lang="scss" scoped>
</style>
<script>
export default {};
</script>
